package com.example.filmguide.logic.network.allperformance


import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class AllPerformanceResponse(
    val code: Int,
    val msg: String,
    val data: List<PerformanceData>,
    val paging: Paging,
    @SerializedName("attrMaps") val attrMaps: AttrMaps,
    val success: Boolean
) : Serializable {

    data class PerformanceData(
        @SerializedName("performanceId") val performanceId: Long,
        @SerializedName("ticketStatus") val ticketStatus: Int,
        @SerializedName("categoryId") val categoryId: Int,
        @SerializedName("shopId") val shopId: String,
        val name: String,
        @SerializedName("shopName") val shopName: String,
        val lat: Double,
        val lng: Double,
        val address: String,
        @SerializedName("posterUrl") val posterUrl: String,
        @SerializedName("postUrlForShare") val postUrlForShare: String,
        @SerializedName("showTimeRange") val showTimeRange: String,
        @SerializedName("priceRange") val priceRange: String,
        @SerializedName("sellPriceRange") val sellPriceRange: String?,
        @SerializedName("seatUrl") val seatUrl: String?,
        val limit: Boolean,
        @SerializedName("inventoryCount") val inventoryCount: Int,
        @SerializedName("tipForList") val tipForList: Any?,
        @SerializedName("performanceLabelVO") val performanceLabelVO: PerformanceLabelVO,
        val detail: String?,
        @SerializedName("travelGuide") val travelGuide: Boolean,
        val summary: String?,
        @SerializedName("ticketNotes") val ticketNotes: String?,
        @SerializedName("cityId") val cityId: Int,
        @SerializedName("cityName") val cityName: String,
        @SerializedName("lowestPrice") val lowestPrice: Double,
        @SerializedName("lowestTicketPrice") val lowestTicketPrice: Any?,
        @SerializedName("lowestSellPrice") val lowestSellPrice: Any?,
        @SerializedName("performanceTag") val performanceTag: Any?,
        @SerializedName("minDiscount") val minDiscount: String?,
        @SerializedName("seatType") val seatType: Int,
        @SerializedName("saleRemindVO") val saleRemindVO: Any?,
        @SerializedName("shareLink") val shareLink: String,
        @SerializedName("stockOutRegister") val stockOutRegister: Int,
        @SerializedName("needAnswer") val needAnswer: Int,
        @SerializedName("questionBankId") val questionBankId: Int,
        @SerializedName("questionHint") val questionHint: Any?,
        @SerializedName("isCurrentCity") val isCurrentCity: Int,
        @SerializedName("distance") val distance: Double,
        val poi: String,
        val self: Boolean,
        @SerializedName("thirdPartyDesc") val thirdPartyDesc: Any?,
        @SerializedName("bsPerformanceId") val bsPerformanceId: Int,
        @SerializedName("tpId") val tpId: Int,
        @SerializedName("needPreInput") val needPreInput: Boolean,
        @SerializedName("kingHonorParam") val kingHonorParam: Any?,
        @SerializedName("needRemindPrice") val needRemindPrice: Boolean,
        @SerializedName("ticketPriceList") val ticketPriceList: Any?,
        @SerializedName("currentLimit") val currentLimit: Boolean,
        @SerializedName("modelStyle") val modelStyle: Int,
        @SerializedName("only") val only: Boolean,
        @SerializedName("needRealName") val needRealName: Boolean,
        @SerializedName("maxBuyLimitPerId") val maxBuyLimitPerId: Int,
        @SerializedName("generalAgent") val generalAgent: Int,
        @SerializedName("exclusive") val exclusive: Int,
        @SerializedName("maxBuyLimitPerOrder") val maxBuyLimitPerOrder: Int,
        @SerializedName("maxBuyLimitPerUser") val maxBuyLimitPerUser: Int,
        @SerializedName("projectVideoVO") val projectVideoVO: Any?,
        @SerializedName("isAssemble") val isAssemble: Boolean?,
        @SerializedName("projectDetailAssembleVO") val projectDetailAssembleVO: Any?,
        @SerializedName("priceRangeType") val priceRangeType: Int,
        @SerializedName("projectExtendVO") val projectExtendVO: ProjectExtendVO?,
        @SerializedName("preview") val preview: Boolean,
        @SerializedName("shareTitle") val shareTitle: String?,
        @SerializedName("promotional") val promotional: Any?,
        @SerializedName("needCloseDetail") val needCloseDetail: Boolean,
        @SerializedName("needCloseRecommend") val needCloseRecommend: Boolean,
        @SerializedName("brightPointList") val brightPointList: Any?,
        @SerializedName("photoStageList") val photoStageList: Any?,
        @SerializedName("videoList") val videoList: Any?,
        @SerializedName("musicList") val musicList: Any?,
        @SerializedName("serviceTitleList") val serviceTitleList: Any?,
        @SerializedName("buttonToast") val buttonToast: Any?,
        @SerializedName("brightName") val brightName: Any?,
        @SerializedName("videoStageName") val videoStageName: Any?,
        @SerializedName("videoStagePhotoTotal") val videoStagePhotoTotal: Any?,
        @SerializedName("videoNum") val videoNum: Int,
        @SerializedName("photoNum") val photoNum: Int,
        @SerializedName("projectServing") val projectServing: Any?,
        @SerializedName("projectStartTime") val projectStartTime: Any?,
        @SerializedName("projectEndTime") val projectEndTime: Any?,
        @SerializedName("robType") val robType: Any?,
        @SerializedName("celebrityVOS") val celebrityVOS: Any?,
        @SerializedName("memberInfo") val memberInfo: Any?,
        @SerializedName("intendedNum") val intendedNum: Int,
        @SerializedName("reachRobStandard") val reachRobStandard: Boolean,
        @SerializedName("unusualSaleStatus") val unusualSaleStatus: Int,
        @SerializedName("relievedTagVO") val relievedTagVO: Any?,
        @SerializedName("tags") val tags: Any?,
        @SerializedName("recommendStatus") val recommendStatus: Int,
        @SerializedName("minTicketOrSellPrice") val minTicketOrSellPrice: Double,
        @SerializedName("multipleReward") val multipleReward: Any?,
        @SerializedName("showMemReward") val showMemReward: Any?,
        @SerializedName("score") val score: String,
        @SerializedName("star") val star: Int,
        @SerializedName("shortName") val shortName: String,
        @SerializedName("normalTags") val normalTags: Any?,
        @SerializedName("playTime") val playTime: Int,
        @SerializedName("playerMinNumLimit") val playerMinNumLimit: Int,
        @SerializedName("playerMaxNumLimit") val playerMaxNumLimit: Int,
        @SerializedName("saleShowNum") val saleShowNum: Int,
        @SerializedName("saleType") val saleType: Int,
        @SerializedName("labelId") val labelId: String?,
        @SerializedName("cornerDisplayName") val cornerDisplayName: String,
        @SerializedName("topType") val topType: Int,
        @SerializedName("billBoardVO") val billBoardVO: Any?,
        @SerializedName("buyInstructionType") val buyInstructionType: Any?,
        @SerializedName("discountTag") val discountTag: String?,
        @SerializedName("condRefund") val condRefund: Int,
        @SerializedName("brandId") val brandId: Any?,
        @SerializedName("brandName") val brandName: Any?,
        @SerializedName("couponDiscount") val couponDiscount: Any?,
        @SerializedName("couponMinSellPrice") val couponMinSellPrice: Any?,
        @SerializedName("couponTicketPrice") val couponTicketPrice: Any?,
        @SerializedName("couponTicketCount") val couponTicketCount: Any?,
        @SerializedName("couponActivityVO") val couponActivityVO: Any?,
        @SerializedName("couponActivityTagVO") val couponActivityTagVO: Any?,
        @SerializedName("couponItemVOList") val couponItemVOList: Any?,
        @SerializedName("isNewMode") val isNewMode: Int,
        @SerializedName("jumpDetailUrl") val jumpDetailUrl: String,
        @SerializedName("relationGroupPurchaseVO") val relationGroupPurchaseVO: Any?,
        @JvmField @SerializedName("celebrityRelationVOS") val celebrityRelationVOS: List<Any>,
        @SerializedName("saleStatus") val saleStatus: Int,
        @SerializedName("promotionVO") val promotionVO: PromotionVO?,
        @SerializedName("hasPromotion") val hasPromotion: Any?,
        @SerializedName("minSellPrice") val minSellPrice: Any?,
        @SerializedName("kingHonorFlag") val kingHonorFlag: Boolean,
        @SerializedName("stockOut") val stockOut: Boolean
    ) : Serializable

    data class PerformanceLabelVO(
        @SerializedName("priceLabel") val priceLabel: Int,
        @SerializedName("contentLabel") val contentLabel: Int,
        @SerializedName("saleLabel") val saleLabel: Int,
        @SerializedName("billBoardLabel") val billBoardLabel: Any?
    ) : Serializable

    data class ProjectExtendVO(
        @SerializedName("projectId") val projectId: Long,
        @SerializedName("maxDiscSetTicketId") val maxDiscSetTicketId: Int,
        @SerializedName("maxDiscSetValue") val maxDiscSetValue: Any?,
        @SerializedName("maxDiscSetTicketPrice") val maxDiscSetTicketPrice: Any?,
        @SerializedName("maxDiscSetTicketSellPrice") val maxDiscSetTicketSellPrice: Any?,
        @SerializedName("maxDiscTicketSetNumber") val maxDiscTicketSetNumber: Int,
        @SerializedName("maxDiscSingleValue") val maxDiscSingleValue: String?,
        @SerializedName("maxDiscSingleTicketId") val maxDiscSingleTicketId: Int,
        @SerializedName("maxDiscSingleTicketPrice") val maxDiscSingleTicketPrice: Any?,
        @SerializedName("maxDiscSingleTicketSellPrice") val maxDiscSingleTicketSellPrice: String?,
        @SerializedName("activityId") val activityId: Any?,
        @SerializedName("maxDiscAssembleTicketId") val maxDiscAssembleTicketId: Int,
        @SerializedName("maxDiscAssemblePrice") val maxDiscAssemblePrice: Any?,
        @SerializedName("maxDiscAssembleValue") val maxDiscAssembleValue: Any?,
        @SerializedName("maxDiscAssembleTicketSellPrice") val maxDiscAssembleTicketSellPrice: Any?,
        @SerializedName("maxDiscAssembleTicketPrice") val maxDiscAssembleTicketPrice: Any?,
        @SerializedName("minTicketOrSellPrice") val minTicketOrSellPrice: Any?,
        @SerializedName("discTicketOriginalPrice") val discTicketOriginalPrice: Any?,
        @SerializedName("discTicketOriginalValue") val discTicketOriginalValue: Any?
    ) : Serializable

    data class Paging(
        @SerializedName("pageNo") val pageNo: Int,
        @SerializedName("pageSize") val pageSize: Int,
        @SerializedName("totalHits") val totalHits: Int,
        @SerializedName("hasMore") val hasMore: Boolean
    ) : Serializable

    data class AttrMaps(
        @SerializedName("serverTime") val serverTime: Long
    ) : Serializable

    data class PromotionVO(
        @SerializedName("promotionTags") val promotionTags: List<Any>?,
        @SerializedName("minSellPrice") val minSellPrice: String,
        @SerializedName("maxSellPrice") val maxSellPrice: String
    ) : Serializable
}