package com.example.filmguide.logic.network.moviedetail

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

@Entity(tableName = "movies")
data class MovieEntity(
    @PrimaryKey(autoGenerate = true) val dbId: Int = 0,
    val availableEpisodes: Int = 0,
    val awardUrl: String = "",
    val backgroundColor: String = "",
    val bingeWatch: Int = 0,
    val bingeWatchst: Int = 0,
    val cat: String = "",
    val comScorePersona: Boolean = false,
    val commented: Boolean = false,
    val dir: String = "",
    val dra: String = "",
    val dur: Int = 0,
    val egg: Boolean = false,
    val enm: String = "",
    val episodeDur: Int = 0,
    val episodes: Int = 0,
    val globalReleased: Boolean = false,
    val guideToWish: Boolean = false,
    val id: Int = 0,
    val imageUrl: String = "",
    val latestEpisode: Int = 0,
    val movieType: Int = 0,
    val multiPub: Boolean = false,
    val musicNum: Int = 0,
    val name: String = "",
    val onSale: Boolean = false,
    val onlinePlay: Boolean = false,
    val orderSt: Int = 0,
    val oriLang: String = "",
    val pn: Int = 0,
    val preScorePersona: Boolean = false,
    val proScore: Int = 0,
    val proScoreNum: Int = 0,
    val pubDate: Long = 0,
    val pubDesc: String = "",
    val rt: String = "",
    val sc: Double = 0.0,
    val scm: String = "",
    val scoreLabel: String = "",
    val showst: Int = 0,
    val snum: Int = 0,
    val src: String = "",
    val star: String = "",
    val trailerStyle: Int = 0,
    val type: Int = 0,
    val typeDesc: String = "",
    val vd: String = "",
    val ver: String = "",
    val videoImg: String = "",
    val videoName: String = "",
    val videourl: String = "",
    val viewedSt: Int = 0,
    val vnum: Int = 0,
    val vodFreeSt: Int = 0,
    val vodPlay: Boolean = false,
    val vodSt: Int = 0,
    val watched: Int = 0,
    val wish: Int = 0,
    val wishst: Int = 0,
    val version: String = ""
) : Serializable

fun convertDetailMovieToMovieEntity(detailMovie: DetailMovie): MovieEntity {
    return MovieEntity(
        availableEpisodes = detailMovie.availableEpisodes,
        awardUrl = detailMovie.awardUrl,
        backgroundColor = detailMovie.backgroundColor,
        bingeWatch = detailMovie.bingeWatch,
        bingeWatchst = detailMovie.bingeWatchst,
        cat = detailMovie.cat,
        comScorePersona = detailMovie.comScorePersona,
        commented = detailMovie.commented,
        dir = detailMovie.dir,
        dra = detailMovie.dra,
        dur = detailMovie.dur,
        egg = detailMovie.egg,
        enm = detailMovie.enm,
        episodeDur = detailMovie.episodeDur,
        episodes = detailMovie.episodes,
        globalReleased = detailMovie.globalReleased,
        guideToWish = detailMovie.guideToWish,
        id = detailMovie.id,
        imageUrl = detailMovie.imageUrl,
        latestEpisode = detailMovie.latestEpisode,
        movieType = detailMovie.movieType,
        multiPub = detailMovie.multiPub,
        musicNum = detailMovie.musicNum,
        name = detailMovie.name,
        onSale = detailMovie.onSale,
        onlinePlay = detailMovie.onlinePlay,
        orderSt = detailMovie.orderSt,
        oriLang = detailMovie.oriLang,
        pn = detailMovie.pn,
        preScorePersona = detailMovie.preScorePersona,
        proScore = detailMovie.proScore,
        proScoreNum = detailMovie.proScoreNum,
        pubDate = detailMovie.pubDate,
        pubDesc = detailMovie.pubDesc,
        rt = detailMovie.rt,
        sc = detailMovie.sc,
        scm = detailMovie.scm,
        scoreLabel = detailMovie.scoreLabel,
        showst = detailMovie.showst,
        snum = detailMovie.snum,
        src = detailMovie.src,
        star = detailMovie.star,
        trailerStyle = detailMovie.trailerStyle,
        type = detailMovie.type,
        typeDesc = detailMovie.typeDesc,
        vd = detailMovie.vd,
        ver = detailMovie.ver,
        videoImg = detailMovie.videoImg,
        videoName = detailMovie.videoName,
        videourl = detailMovie.videourl,
        viewedSt = detailMovie.viewedSt,
        vnum = detailMovie.vnum,
        vodFreeSt = detailMovie.vodFreeSt,
        vodPlay = detailMovie.vodPlay,
        vodSt = detailMovie.vodSt,
        watched = detailMovie.watched,
        wish = detailMovie.wish,
        wishst = detailMovie.wishst,
        version = detailMovie.version
    )
}